csv_file="heart.csv"
tex_file="heart_table.tex"


cat<< EOF > $tex_file
\documentclass{article}
\usepackage{geometry}
\geometry{a4paper, margin=1in}
\usepackage{longtable}

\title{Heart Data Table}
\author{Generated by $csv_file}

\begin{document}
\maketitle
\begin{longtable}{|c|c|c|c|c|c|c|c|c|c|c|c|c|c|}
\caption{Heart Table} \\\\
\hline
EOF

while IFS=',' read -r age sex cp trestbps chol fbs restecg thalach exang oldpeak slope ca thal target; do
    if [ "$age" = "age" ]; then
        echo "\\textbf{$age} & \\textbf{$sex} & \\textbf{$cp} & \\textbf{$trestbps} & \\textbf{$chol} & \\textbf{$fbs} & \\textbf{$restecg} & \\textbf{$thalach} & \\textbf{$exang} & \\textbf{$oldpeak} & \\textbf{$slope} & \\textbf{$ca} & \\textbf{$thal} & \\textbf{$target} \\\\ \hline" >> $tex_file
    else
        echo "$age & $sex & $cp & $trestbps & $chol & $fbs & $restecg & $thalach & $exang & $oldpeak & $slope & $ca & $thal & $target \\\\ \hline" >> $tex_file
    fi
done < "$csv_file"

cat<<EOF >> $tex_file
\end{longtable}
\end{document}
EOF

pdflatex $tex_file
