csv_file="heart.csv"
tex_file="heart_table.tex"


cat<< EOF > $tex_file
\documentclass{article}
\usepackage{geometry}
\geometry{a4paper, margin=1in}
\usepackage{longtable}

\title{Heart Data Table}
\author{Generated by $csv_file}

\begin{document}
\maketitle
\begin{longtable}{|c|c|c|c|c|c|c|c|}
\caption{Heart Table} \\\\
\hline
EOF

while IFS=',' read -r Age Sex ChestPain BloodPressure Cholesterol BloodSugar MaxHeartRate HeartDisease; do
    if [ "$age" = "Age" ]; then
        echo "\\textbf{$Age} & \\textbf{$Sex} & \\textbf{$ChestPain} & \\textbf{$BloodPressure} & \\textbf{$Cholesterol} & \\textbf{$BloodSugar} & \\textbf{$MaxHeartRate} & \\textbf{$HeartDisease} \\\\ \hline" >> $tex_file
    else
        echo "$Age & $Sex & $ChestPain & $BloodPressure & $Cholesterol & $BloodSugar & $MaxHeartRate & $HeartDisease \\\\ \hline" >> $tex_file
    fi
done < "$csv_file"

cat<<EOF >> $tex_file
\end{longtable}
\end{document}
EOF

pdflatex $tex_file
